# optimize instance class (F1 is cheapest/default, F2/F4 are faster)
instance_class: F1

# automatic scaling setting to control costs
automatic_scaling:
  max_instances: 5
  min_instances: 1
  min_idle_instances: 0

runtime: nodejs22

env_variables:
  CORS_ORIGIN: "https://gregwiley.dev"
  GCP_PROJECT_ID: "gregwiley-dev"